# Generated by Django 3.1.7 on 2021-03-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KataMereka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img_mereka', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('time_upload', models.DateField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='img')),
                ('publish', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TambahMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=70)),
                ('pekerjaan', models.TextField()),
                ('img_member', models.ImageField(upload_to='member')),
            ],
        ),
        migrations.CreateModel(
            name='TambahProduk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=3, max_digits=9)),
                ('img_produk', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Testimoni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('jabatan', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='video')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'video',
            },
        ),
    ]
