# Generated by Django 3.1.7 on 2021-03-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaf', '0003_katamereka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('Video', models.FileField(upload_to='video')),
            ],
        ),
    ]
