# Generated by Django 3.1.7 on 2021-03-25 03:19

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leaf', '0004_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='Video',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
