# Generated by Django 3.1.7 on 2021-03-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaf', '0005_auto_20210325_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='Video',
            field=models.FileField(upload_to='video'),
        ),
    ]
