# Generated by Django 3.1.7 on 2021-03-25 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaf', '0006_auto_20210325_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'video', 'verbose_name_plural': 'video'},
        ),
        migrations.RenameField(
            model_name='video',
            old_name='Video',
            new_name='video',
        ),
    ]
